### ISSUE TITLE
Languages lost after migrating from 1.0.5 to 1.5.0.8/1.6.0

### ISSUE THREAD

**Issue by MartinWunderli** [pellcorp/opendb#80]
Hi,

Some language/format combinations and therefore some languages are lost during the migration.

In 1.0.5: 
![languages_1 5](https://cloud.githubusercontent.com/assets/14999963/10389230/27602178-6e70-11e5-928f-a7f0fbf4a2ce.PNG)

In 1.6.0:
![languages_1 6](https://cloud.githubusercontent.com/assets/14999963/10389244/332e5d1c-6e70-11e5-88ea-e0fc30ae9c44.PNG)

**Comment by MartinWunderli** [comment]
I think I should elaborate a bit on the issue: In 1.0.x, there was a single field for language and audio type, e.g. English_5.1, German_2.1 etc. During migration from 1.0.x to 1.5.x, this field was split into Audio Language and Audio Format AND (some) data (probably only the English entries) were tried to be migrated.

Issue one: The situation with different audio formats for different languages (e.g. a film with English_5.1 and German_2.1) cannot be entered precisely any more. One does not know, which audio format belongs to which language(s) if one enters Audio Language English,German and Audio Format 5.1, 2.1. However, I do not think that this can be easily fixed (especially with data already entered) and it is probably acceptable to have that slight information loss.

Issue two: During migration, languages are dropped as shown above. This should be fixable.

**Comment by pellcorp** [comment]
I am going to release a 1.5.0.9 which you should use to upgrade from 1.0.5, don't upgrade via 1.5.0.7.  I will remove the upgrade step that changes these formats.  I will then upgrade master to handle both the old and new formats (for those already upgraded) in import and site plugins and anywhere else required.   I hope to look at this later on tonight.

**Comment by pellcorp** [comment]
Hi,

I have updated the RELEASE-1.5.0 branch with changes to remove the DVD_AUDIO migration from AUDIO_LANG.  I left in the migration of some options to AUDIO_XTRA (such as directors commentary), because I think that's a good change.

I have not created a tag as yet, I wanted you to test out my changes first and let me know how you go:

https://github.com/pellcorp/opendb/archive/RELEASE-1.5.0.zip

Following that you can get the latest 1.6.1 which has a few changes to site plugins to revert back to audio_lang instead of dvd_audio.  There is an upgrade script which will migrate the db from dvd_audio back to audio_lang as well which will be executed as part of the upgrade, but obviously won't affect you

https://github.com/pellcorp/opendb/archive/master.zip

The migration back to AUDIO_LANG will result in lost information if you upgrade from 1.5.0.7, please go back and upgrade from 1.0.5 DIRECTLY to 1.5.0.9, and then directly to 1.6.1

Please let me know if this is sufficient

**Comment by pellcorp** [comment]
Actually if you can first of all just run the upgrade against 1.5.0.7, I don't actually think there will be any data loss, at least not in your data.  Let me know if the 1.6.1 upgrade restores what you were expecting.

**Comment by MartinWunderli** [comment]
It would be 1.5.0.8, ok?

Cheers
Martin

**Comment by pellcorp** [comment]
yep that's fine, it will be helpful if you can confirm my 1.6.1 upgrade works from a version before 1.5.0.9 which removes the DVD_AUDIO.

But its up to you obviously which route you go, I just want to be confident I have not broken anything for other users.

**Comment by pellcorp** [comment]
Upgrading from 1.6.0 to 1.6.1 would be a great test too

**Comment by MartinWunderli** [comment]
Ok, easy things first.

I did a fresh upgrade from 1.5.0.8 to 1.6.0 to be sure to have a clean 
1.6.0. Then I did an upgrade to 1.6.1, AUDIO lang was back (of course 
the data lost between 1.0.5 and 1.5.0.8 did not reappear... ;-) ;-)). 
System seems to work, fine.

Cheers
Martin

**Comment by MartinWunderli** [comment]
Hi,

Great!

I started with a restore of my 1.0.5. Then I did the upgrade to 1.5.0.9 
(you call it RELEASE-1.5.0.zip). AUDIO_LANG entries were there, sorting 
ok. Then I did the upgrade to 1.6.1, AUDIO_LANG still there (although I 
was surprised about a message during migration which said 'back to 
AUDIO_LANG'), sorting still ok. Added a Disk via AMAZON.DE, some quirks 
but no big deal.

So I am really happy about the result. If you need anymore testing or 
database dumps/software directories, just ask.

Cheers
Martin

**Comment by pellcorp** [comment]
Report any issues with amazon.de and we can see if we can fix them.

**Comment by pellcorp** [comment]
I have released versions 1.5.0.9 and 1.6.1
